#写你的群号
QQ: '1231231231231'


#===========================================================
#
#                           注意
#  本插件的敏感词库为动态更新，请留意网站，禁止倒卖，原作者Minloha。
#插件内部集成一套算法，完全不需要修改配置文件你就可以在游戏中对敏感
#字符库进行添加。
#  插件出现问题了？加我QQ:2821163570，获取免费插件请到我的网站下载
#www.hanxiangyu.xyz，如果卡顿请刷新.
#  在1.2.2版本中内含举报功能，距离检测功能，关键词屏蔽与自动封禁系统
#如果有违规行为会在控制台输出，请及时查看
#
#使用时切记要安装placeholderAPI
#
#
#
#==============================================================

#我爱了......



#踢出多少次服务器就会被封禁
BanTime: 3

#敏感词列表，按照格式写，错了会崩溃,不建议修改,敏感列表随时更新
terms:
  - '肏你妈屄'
  - '你奶奶个蛋'
  - '死孩子'
  - '颦熊'
  - 'nmsl'
  - '你妈死了'
  - 'cnm'
  - '傻逼'
  - '小鸡巴航航子'
  - '操你妈'
  - '处女膜'
  - 'wdnmd'
  - '我是你爸爸'
  - '我是你妈妈'
  - '我是你爸'
  - '我是你妈'
  - '妈的'
  - '马的'
  - '你的逼真爽'
  - '嫖娼'
  - '好多毛'
  - '葵花宝典'
  - 'wtm'
  - '爷轮奸'
  - '你麻痹‘
  - 'Wtm'
  - 'wTm'
  - 'wtM'
  - 'WTm'
  - 'wTM'
  - 'WTM'
  - '骨灰'
  - '鸡巴'
  - 'jb'
  - 'j8'
  - 'tm'
  - '他妈'
  - '她妈'
  - 'sgm'
  - 'Sgm'
  - 'nm$l'
  - 'nm'
  - '$b'
  - '$B'
  - 'loser'
  - 'sGm'
  - 'sgM'
  - 'SGm'
  - 'sGM'
  - 'SGM'
  - '死个妈'
  - '阴道'
  - '安乐'
  - '娇喘'
  - '卖身'
  - '妓'
  - '坐飞机'
  - '一夜情'
  - '阴部'
  - '阴唇'
  - '阴户'
  - '阴核'
  - '精子'
  - '母'
  - '乳'
  - '自慰'
  - '做爱'
  - '法轮功'
  - '垃圾'
  - 'nmd'
  - 'Nmd'
  - 'nMd'
  - 'nmD'
  - 'NMd'
  - 'nMD'
  - 'NMD'
  - 'jb'
  - 'Jb'
  - 'jB'
  - 'JB'
  - '脑抽'
  - '死妈'
  - '死马'
  - 'sm'
  - 'Sm'
  - 'sM'
  - 'SM'
  - '啥也不是'
  - 'cpdd'
  - 'Cpdd'
  - 'cPdd'
  - 'cpDd'
  - 'cpdD'
  - 'CPdd'
  - 'cPDd'
  - 'cpDD'
  - 'CPDd'
  - 'cPDD'
  - 'CPDD'
  - 'cdx'
  - '处对象'
  - '啪啪啪'
  - '强奸'
  - '嫖老师'
  - 'cgx'
  - 'byt'
  - '飞机杯'
  - '狗儿子'
  - '约炮'
  - '轮奸'
  - '特么的'
  - '撕逼'
  - '妈蛋'
  - '婊子'
  - '婊砸'
  - 'caonima'
  - 'caonm'
  - 'nmb'
  - 'goubi'
  - '日了狗'
  - '你妹'
  - '碧池'
  - '我靠'
  - 'nimade'
  - 'nmd'
  - 'Nmd'
  - 'nMd'
  - 'nmD'
  - 'NMd'
  - 'nMD'
  - 'NMD'
  - '买了个表'
  - 'wotama'
  - 'ma'
  - 'caonimua'
  - '娘'
  - '迷你世界'
  - 'jj'
  - 'JJ'
  - '操爆你'
  - '妹妹b好粉呀'
  - '好紧啊'
  - '啊~啊~啊~'
  - '谈爱'
  - '杀你妈'
  - '你妈呢'
  - 'Mb'
  - '冥币'
  - '烧钱'
  - 'rnmb'
  - '你妹的'
  - 'Whore'
  - '搞关系'
  - '你配吗'
  - 'ppp'
  - 'dnm'
  - 'papapa'
  - 'wdsnm'
  - 'cai'
  - 'jj'